### ISSUE TITLE
Introduce stable branch

### ISSUE THREAD

**Issue by spikespaz** [nix-community/nix-vscode-extensions#19]
I propose that we track problematic extensions (looking at `rust-analyzer`) and only push these specific extensions to the stable branch when they have been checked after an automatic update.
```
specified: sha256-ttLGbPikx3khbjRiubNjlkEF5uX/T3NkpdpSCbELEKw=
got:       sha256-VHBxuVz7Dul/yIRnlhep3sKx9qCOOexVjLciBB1c23Y=
```

**Comment by AmeerTaweel** [comment]
Is the problem with `rust-analyzer` specific to some versions? If I understand correctly, the issue is that we get files for different platforms some times. In that case, this is independent of the version. Even if we test the extension and it works, a user might still get a wrong hash later.

Please correct me if I'm wrong.

**Comment by spikespaz** [comment]
https://github.com/nix-community/nix-vscode-extensions/issues/5

**Comment by spikespaz** [comment]
What versions are different? Is it random? What do you mean different platforms? I might get a vsix for a different architecture, platform, or system double?
